name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: |
          cargo test --all-features
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Auto-merge minor and patch updates
        if: success()
        run: |
          # Get PR details
          PR_TITLE="${{ github.event.pull_request.title }}"
          
          # Check if it's a minor or patch update
          if echo "$PR_TITLE" | grep -E "(bump|update).*from.*to.*\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$"; then
            echo "This is a minor or patch update, auto-merging..."
            gh pr merge ${{ github.event.pull_request.number }} --auto --squash
          else
            echo "This is a major update, manual review required"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
